spring:
  application:
    name: ledgerview
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations:
      - classpath:/db/migration

application:
  palette:
    default-color: '#6366F1'
    colors:
      - '#6366F1'
      - '#3B82F6'
      - '#0EA5E9'
      - '#06B6D4'
      - '#10B981'
      - '#84CC16'
      - '#F59E0B'
      - '#F97316'
      - '#EF4444'
      - '#EC4899'
      - '#A855F7'
      - '#64748B'
